chat/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name='chat'

urlpatterns = [
    path('', views.all_conv, name='all_conv'),
    path('<str:room_name>/', views.room, name='room'),
    path('logout', views.logout, name='logout')
]

chatapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

class User(models.Model):
    name = models.CharField(max_length=20)
    phone = models.CharField(max_length=15, unique=True)

    def __str__(self):
        return self.name

class Contact(models.Model):
    user = models.ForeignKey(User, related_name='friends', on_delete=models.CASCADE)
    friends = models.ManyToManyField('self', blank=True)
    
    def __str__(self):
        return self.user.name


class Message(models.Model):
    contact = models.ForeignKey(Contact, related_name = 'messages', on_delete = models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add = True )
    # picture = models.FileField(upload_to='attachments/')

    def __str__(self):
        return '[{timestamp}] {contact}: {content}'.format(**self.as_dict())
    
    def as_dict(self):
        return {'contact': self.contact, 'content': self.content, 'timestamp': self.timestamp}

class Chat(models.Model):
    participants = models.ManyToManyField(Contact, related_name='chats')
    messages = models.ManyToManyField(Message, blank=True)

    def __str__(self):
        return '{}'.format(self.pk)

chat/views.py
from django.shortcuts import render, redirect
import json
from django.contrib import messages
from django.utils.safestring import mark_safe
from django.shortcuts import render
from .models import User, Contact, Message, Chat

def index(request):
    return render(request, 'chat/index.html')

def get_user_contact(phone):
    try:
        user = User.objects.get(phone = phone)
    except User.DoesNotExist:
        user = None
    try:
        contact = Contact.objects.get(user = user)
    except Contact.DoesNotExist:
        contact = None

    return contact

def get_user_chats(request):
    phone = request.session.get('user', None)
    contact = get_user_contact(phone)
    if contact:
        return contact.chats.all()
    else:
        return None

def last_30_messages(chatID):
    try:
        chat = Chat.objects.get(id = chatID)
        return chat.messages.order_by('-timestamp').all()[:30]
    except Chat.DoesNotExist:
        return None
    


def room(request, room_name):
      
    if request.POST.get('user_submit'):
        if User.objects.filter(phone = request.POST.get('user_phone'), name = request.POST['user_name']).exists():
            user = User.objects.get(phone = request.POST.get('user_phone'), name = request.POST['user_name'])
            user_contact = Contact.objects.get(user = user)
            messages.success(request, 'User Logged in successfully!')
        else:
            user = User.objects.create(phone = request.POST.get('user_phone'), name = request.POST['user_name'])
            user_contact = Contact.objects.create(user = user)
            messages.success(request, 'User Created successfully!')
        
        request.session['user'] = user.phone

    try:
        user = User.objects.get(phone = request.session.get('user', None))
        user_contact = Contact.objects.get(user = user)
    except User.DoesNotExist:
        user = None
        return render(request, 'chat/all_conv.html', {
            'username': mark_safe(json.dumps(request.session.get('user', None))),
            'user_obj': user,
        })

    chat = Chat.objects.get(id = room_name) 
    chat_participants = list(chat.participants.all())
    chat_participants.remove(user_contact)
    chat_edited = {
        'chat': chat,
        'other_user': chat_participants[0]
    }

        
    print(request.session.items())
    return render(request, 'chat/chat_inner.html', {
        'room_name_json': mark_safe(json.dumps(room_name)),
        'username': mark_safe(json.dumps(request.session.get('user', None))),
        'user_obj': user,
        'is_recent_active':'active',
        'chat':chat_edited,
    })

def all_conv(request):
      
    if request.POST.get('user_submit'):
        if User.objects.filter(phone = request.POST.get('user_phone'), name = request.POST['user_name']).exists():
            user = User.objects.get(phone = request.POST.get('user_phone'), name = request.POST['user_name'])
            user_contact = Contact.objects.get(user = user)
            messages.success(request, 'User Logged in successfully!')
        else:
            user = User.objects.create(phone = request.POST.get('user_phone'), name = request.POST['user_name'])
            user_contact = Contact.objects.create(user = user)
            messages.success(request, 'User Created successfully!')
        
        request.session['user'] = user.phone

    try:
        user = User.objects.get(phone = request.session.get('user', None))
        user_contact = Contact.objects.get(user = user)
    except User.DoesNotExist:
        user = None
        return render(request, 'chat/all_conv.html', {
            'username': mark_safe(json.dumps(request.session.get('user', None))),
            'user_obj': user,
        })
    
    print(request.session.items())

    chats = get_user_chats(request)
    chats_edited = []
    for chat in chats:
        chat_participants = list(chat.participants.all())
        chat_participants.remove(user_contact)
        chats_edited.append({
            'chat': chat,
            'other_user': chat_participants[0]
        })
    
    return render(request, 'chat/all_conv.html', {
        'username': mark_safe(json.dumps(request.session.get('user', None))),
        'user_obj': user,
        'is_all_active': 'active',
        'user_chats': chats_edited,
    })

def logout(request):
    request.session.pop('user', None)
    print(request.session.items())
    return redirect('chat:all_conv')

chat/templates/chat/all_conv.html
{% extends 'chat/room.html' %}

{% block chat_inner %}
    
<div class="wrapper px-2 py-3">
    <h3 class="text-center">List of Contacts</h3>
    <div class="container ">
        <div class="row justify-content-center">
            
            {% for item in user_chats %}
            <div class="card ml-2 mr-2 mt-4" >
                <div class="card-body" style="width: 150px;">
                  <h5 class="card-title">{{ item.other_user.user.name }}</h5>
                  <h6 class="card-subtitle mb-4 mt-3 text-muted"><i class="fa fa-phone"></i> {{ item.other_user.user.phone }}</h6>
                  <a href="{% url 'chat:room' item.chat.id %}" class="card-link"><button class="btn btn-primary">Chat</button></a>
                </div>
            </div>
            {% endfor %}
                



        </div>
    </div>
</div>

{% load static %}
<script src="{% static 'chat/reconnecting-websocket.min.js' %}"></script>
<script>
    const roomName = 999999;
    const username = {{ username }};
    
    const chatSocket = new ReconnectingWebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/'
        + roomName
        + '/'
    );

    chatSocket.onopen = function(e) {
      fetchMessages();
    }

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        console.log(data)
        if (data['command'] === 'messages') {
            if(data['messages']){
                for (let i=0; i<data['messages'].length; i++) {
                  createMessage(data['messages'][i]);
                }
            }
        } else if (data['command'] === 'new_message'){
          createPrependMessage(data['message']);
        } else if (data['command'] === 'got_chat'){
            document.querySelector('#msg_history').innerHTML='';
            if(data['messages']){
                for (let i=0; i<data['messages'].length; i++) {
                  createMessage(data['messages'][i]);
                }
            }
        } else if (data['command'] == 'New_user_not_found'){
            alert('User with phone not found!')
        }
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };


//Handling message to New User 

    document.querySelector('#toMessage').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#toSubmit').click();
        }
    };

    document.querySelector('#toSubmit').onclick = function(e) {
        const messageInputDom = document.querySelector('#toMessage');
        const message = messageInputDom.value;
        const toUser = document.querySelector('#toPhone').value;
        chatSocket.send(JSON.stringify({
            'command': 'to_new_user',
            'message': message,
            'from': username,
            'to': toUser,
        }));
        messageInputDom.value = '';
        document.querySelector('#toPhone').value = '';
    };

    function fetchMessages() {
      chatSocket.send(JSON.stringify({'command': 'get_messages', 'chatID': roomName }));
    }

    function createPrependMessage(data) {
      var author = data['author'];
      var msgListTag = document.createElement('div');
      var msgInnerTag = document.createElement('div');
      var pTag = document.createElement('p');
      var spanTag = document.createElement('span');

      pTag.textContent = data.content;
      var dateTime = getDisplayDate(new Date(data.timestamp));
      spanTag.textContent = dateTime.time + ' | ' + dateTime.date;
      spanTag.className= 'time_date';

      if (author === username) {
        msgListTag.className = 'outgoing_msg';
        msgInnerTag.className = 'sent_msg';
      } else {
        msgListTag.className = 'received_msg';
        msgInnerTag.className = 'received_withd_msg';
      }
      msgInnerTag.appendChild(spanTag);
      msgInnerTag.appendChild(pTag);
      msgListTag.appendChild(msgInnerTag);
      $('#msg_history').prepend(msgListTag);
    }

    function createMessage(data) {
      var author = data['author'];
      var msgListTag = document.createElement('div');
      var msgInnerTag = document.createElement('div');
      var pTag = document.createElement('p');
      var spanTag = document.createElement('span');

      pTag.textContent = data.content;
      var dateTime = getDisplayDate(new Date(data.timestamp));
      spanTag.textContent = dateTime.time + ' | ' + dateTime.date;
      spanTag.className= 'time_date';

      if (author === username) {
        msgListTag.className = 'outgoing_msg';
        msgInnerTag.className = 'sent_msg';
      } else {
        msgListTag.className = 'received_msg';
        msgInnerTag.className = 'received_withd_msg';
      }
      msgInnerTag.appendChild(spanTag);
      msgInnerTag.appendChild(pTag);
      msgListTag.appendChild(msgInnerTag);
      document.querySelector('#msg_history').appendChild(msgListTag);
    }

    function getDisplayDate(date) {
        today = new Date();
        today.setHours(0);
        today.setMinutes(0);
        today.setSeconds(0);
        today.setMilliseconds(0);
        compDate = date; 
        diff = compDate.getTime() - today.getTime(); 
        Time = compDate.getHours()+':'+ ((compDate.getMinutes()<10) ? '0'+compDate.getMinutes() : compDate.getMinutes())
        if (diff >= 0) {
            return {
                date: "Today", 
                time: Time
            };
        } else if (diff < 0 && diff >= -(24 * 60 * 60 *1000)) {
            return{
                date: "Yesterday",
                time: Time
            };
        } else { 
            var dd = compDate.getDate();

            var mm = compDate.getMonth()+1; 
            var yyyy = compDate.getFullYear();
            if(dd<10) {
                dd='0'+dd;
            } 

            if(mm<10) {
                mm='0'+mm;
            } 
            return {
                date: dd+'-'+mm+'-'+yyyy,
                time: Time
            }
        }
    }
</script>
{% endblock chat_inner %}

chat/templates/chat/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}Textify{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,500&display=swap" rel="stylesheet"> <!--Montserrat-->
  {% load static %}
  <link rel="stylesheet" href="{% static 'chat/style.css' %}">
</head>

<body>
  <div class="container main-container">
    <div class="section">
      <div class="row top-line"></div>
      <div class="row">
        <div class="col-10 col-md-11 py-3">
          <h4 class="text-center text-md-left d-none d-md-block"><strong>Textify</strong> Because Text Messaging Rocks</h4>
          <h4 class="text-center text-md-left d-block d-md-none"><strong>Textify</strong> - Texting Rocks</h4>
        </div>
        <div class="col-2 col-md-1 py-3">
          <a href="{% url 'chat:logout' %}" class="d-none d-md-block">Logout</a>
          <a href="{% url 'chat:logout' %}" class="d-block d-md-none"><h3><i class="fa fa-sign-out"></i></h3></a>
        </div>
      </div>
    </div>  
    {% block content %}{% endblock content %}
    {% block afterbody %}{% endblock afterbody %}
    <script src="{% static 'chat/reconnecting-websocket.min.js' %}"></script>
  </div>
  <div class="container mb-5">
    <div class="row">
      <div class="col">
        <small>Textify, <a href="https://www.linkedin.com/in/eswar-prasad-clinton-a-a473441a7/">EswarClynn</a> © 2020</small>
      </div>
      <div class="col text-right">
        <small>All text messaging on this site is kept 100% secure - <a href="">read our security policy.</a></small>
      </div>
    </div>
  </div>
</body>
</html>

chat/templates/chat/chat_inner.html
{% extends 'chat/room.html' %}

{% block chat_inner %}

<div class="wrapper px-2">
    <div class="row pl-2 pl-md-2 py-3">
        <span class="col-10 col-md-4"><h3>{{ chat.other_user.user.name }} - {{ chat.other_user.user.phone }}</h3> </span>
        <span class="col-2 d-block d-md-none"><a href="{% url 'chat:all_conv' %}"><i class="fa fa-users mr-3"></i>All</a></span>
        <span class="col-11 col-md-3 text-muted ml-md-1 mt-1"><a href="">Set a name for this number.</a></span>
        <span class="col-11 col-md-4 text-muted text-right  mt-1 d-none d-md-block"><a href="{% url 'chat:all_conv' %}"><h5>View All conversations >></h5></a></span>
    </div>
    <div class="row">
        <div class="container-fluid ">
            <div class="row ml-2 mb-2 w-100"><span class="col-12"><strong>New Text Message</strong></span></div>
            <div class="row ml-2">
                <div class="col-11 col-md-10 ">
                    <textarea name="message_content" id="chat-message-input"  class="form-control" required></textarea>
                    <small><input type="file" id="chatImage" name="chatImage">Attach a photo to this text message.</a></small>
                </div>
                <div class="col-11 col-md-2">
                    <buttton class="btn btn-primary w-100 py-3" type="submit" name="message_send" id="chat-message-submit" value="message_sending">Send Message</buttton>
                </div>
            </div>
            <div class="container-fluid chatlist-container  mt-3 mb-4">
                <div class="msg_history" id="msg_history">
                </div>
            </div>

        </div>
        </div>
    </div>
</div>

{% load static %}
<script src="{% static 'chat/reconnecting-websocket.min.js' %}"></script>
<script>
    const roomName = {{ room_name_json }};
    const username = {{ username }};
    
    const chatSocket = new ReconnectingWebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/'
        + roomName
        + '/'
    );

    chatSocket.onopen = function(e) {
      fetchMessages();
    }

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        console.log(data)
        if (data['command'] === 'messages') {
          for (let i=0; i<data['messages'].length; i++) {
            createMessage(data['messages'][i]);
          }
        } else if (data['command'] === 'new_message'){
          createPrependMessage(data['message']);
        } else if (data['command'] === 'got_chat'){
            document.querySelector('#msg_history').innerHTML='';
            for (let i=0; i<data['messages'].length; i++) {
                createMessage(data['messages'][i]);
            }
        } else if (data['command'] == 'New_user_not_found'){
            alert('User with phone not found!')
        }
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'command': 'new_message',
            'message': message,
            'from': username,
            'chatID': roomName,
        }));
        messageInputDom.value = '';
    };

//Handling message to New User 

    document.querySelector('#toMessage').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#toSubmit').click();
        }
    };

    document.querySelector('#toSubmit').onclick = function(e) {
        const messageInputDom = document.querySelector('#toMessage');
        const message = messageInputDom.value;
        const toUser = document.querySelector('#toPhone').value;
        chatSocket.send(JSON.stringify({
            'command': 'to_new_user',
            'message': message,
            'from': username,
            'to': toUser,
        }));
        messageInputDom.value = '';
        document.querySelector('#toPhone').value = '';
    };

    function fetchMessages() {
      chatSocket.send(JSON.stringify({'command': 'get_messages', 'chatID': roomName }));
    }

    function createPrependMessage(data) {
      var author = data['author'];
      var msgListTag = document.createElement('div');
      var msgInnerTag = document.createElement('div');
      var pTag = document.createElement('p');
      var spanTag = document.createElement('span');

      pTag.textContent = data.content;
      var dateTime = getDisplayDate(new Date(data.timestamp));
      spanTag.textContent = dateTime.time + ' | ' + dateTime.date;
      spanTag.className= 'time_date';

      if (author === username) {
        msgListTag.className = 'outgoing_msg';
        msgInnerTag.className = 'sent_msg';
      } else {
        msgListTag.className = 'received_msg';
        msgInnerTag.className = 'received_withd_msg';
      }
      msgInnerTag.appendChild(spanTag);
      msgInnerTag.appendChild(pTag);
      msgListTag.appendChild(msgInnerTag);
      $('#msg_history').prepend(msgListTag);
    }

    function createMessage(data) {
      var author = data['author'];
      var msgListTag = document.createElement('div');
      var msgInnerTag = document.createElement('div');
      var pTag = document.createElement('p');
      var spanTag = document.createElement('span');

      pTag.textContent = data.content;
      var dateTime = getDisplayDate(new Date(data.timestamp));
      spanTag.textContent = dateTime.time + ' | ' + dateTime.date;
      spanTag.className= 'time_date';

      if (author === username) {
        msgListTag.className = 'outgoing_msg';
        msgInnerTag.className = 'sent_msg';
      } else {
        msgListTag.className = 'received_msg';
        msgInnerTag.className = 'received_withd_msg';
      }
      msgInnerTag.appendChild(spanTag);
      msgInnerTag.appendChild(pTag);
      msgListTag.appendChild(msgInnerTag);
      document.querySelector('#msg_history').appendChild(msgListTag);
    }

    function getDisplayDate(date) {
        today = new Date();
        today.setHours(0);
        today.setMinutes(0);
        today.setSeconds(0);
        today.setMilliseconds(0);
        compDate = date; 
        diff = compDate.getTime() - today.getTime(); 
        Time = compDate.getHours()+':'+ ((compDate.getMinutes()<10) ? '0'+compDate.getMinutes() : compDate.getMinutes())
        if (diff >= 0) {
            return {
                date: "Today", 
                time: Time
            };
        } else if (diff < 0 && diff >= -(24 * 60 * 60 *1000)) {
            return{
                date: "Yesterday",
                time: Time
            };
        } else { 
            var dd = compDate.getDate();

            var mm = compDate.getMonth()+1; 
            var yyyy = compDate.getFullYear();
            if(dd<10) {
                dd='0'+dd;
            } 

            if(mm<10) {
                mm='0'+mm;
            } 
            return {
                date: dd+'-'+mm+'-'+yyyy,
                time: Time
            }
        }
    }
</script>


{% endblock chat_inner %}

chat/templates/chat/room.html
{% extends 'chat/base.html' %}

{% block content %}

<!-- {% if messages %}                           
{% for message in messages %}
     <script>
          alert('{{message}}');
     </script>
{% endfor %}
{% endif %}
     -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <form method="post">{% csrf_token %}
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Enter Phone No.</h5>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    Name:
                    <input type="text" name="user_name" id="user_name" class="form-control mt-2">
                </div>
                <div class="form-group">
                    Phone No:
                    <input type="text" name="user_phone" id="user_phone" class="form-control mt-2">
                </div>
            </div>
            <div class="modal-footer">
              <button type="submit" class="btn btn-primary" name="user_submit" value="Logging">Login</button>
            </div>
          </div>
        </div>
    </form>
</div>

{% if user_obj == None %}
    <script>$('#exampleModal').modal({backdrop: 'static', keyboard: false})</script>
{% endif %}


<div class="container bg pt-3 pb-5">
    <div class="text-center">
        <h1 class="d-none d-md-block"><i class="fa fa-phone"></i> {{ user_obj.name}} - {{ user_obj.phone }}</h1>
        <h3 class="d-block d-md-none"><i class="fa fa-phone"></i> {{ user_obj.name}} - {{ user_obj.phone }}</h3>

        <a href="" class="text-muted">What's this number?</a>
    </div>
    <div class="container-fluid bg-darkgrey py-3 mt-3  message-container">

            <div class="row pt-2">
                <div class="col-4 col-lg-2 py-2">
                    <p class="text-bigger text-md-right">To:</p>
                </div>
                <div class="col py-1">
                    <input type="text" name="toPhone" id="toPhone" class="form-control form-text d-inline">
                    <span class="text-muted ml-3 d-none d-md-inline"><< Phone number or name</span>
                </div>
            </div>
            <div class="row ">
                <div class="col-4 col-lg-2 py-2">
                    <p class="text-bigger text-right">Message:</p>
                </div>
                <div class="col py-1">
                    <textarea name="toMessage" id="toMessage" class="form-control mr-5" rows="5" cols="10" required></textarea>
                    <small><input type="file" id="topImage" name="topImage">Attach a photo to this text message.</a></small>
                </div>
            </div>
            <div class="row py-2">
                <div class="col-lg-2 py-2">
                </div>
                <div class="col py-1 text-center text-md-left">
                    <button class="btn btn-primary p-3 " id="toSubmit" type="submit">Send Text Message</button>
                    <span class="ml-md-5 text-muted d-block d-md-inline">Or, <a href="" class="text-muted">schedule it for a later delivery.</a></span>

                </div>
            </div>

    </div>
    <div class="chat-container mt-5">
        <ul class="nav nav-tabs w-100 ">
            <li class="nav-item ml-3 ml-md-5 ">
                <a class="nav-link {{ is_recent_active }} d-none d-md-block" href="#">Recent Conversations</a>
                <a class="nav-link {{ is_recent_active }} d-block d-md-none" href="#">Recent</a>
            </li>
            <li class="nav-item ">
                <a class="nav-link {{ is_all_active }} d-none d-md-block" href="{% url 'chat:all_conv' %}">All Conversations</a>
                <a class="nav-link {{ is_all_active }} d-block d-md-none" href="{% url 'chat:all_conv' %}">All</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ is_photos_active }}" href="#">Photos</a>
            </li>
        </ul>

        <div class="bg-lightgrey ">
            {% block chat_inner %}
            {% endblock chat_inner %}
        </div>

    </div>
</div>


{% endblock content %}